# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Initialization.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Initialization(object):
    def setupUi(self, Initialization):
        Initialization.setObjectName("Initialization")
        Initialization.resize(400, 300)
        Initialization.setMinimumSize(QtCore.QSize(400, 300))
        Initialization.setMaximumSize(QtCore.QSize(400, 300))
        self.buttonBox = QtWidgets.QDialogButtonBox(Initialization)
        self.buttonBox.setGeometry(QtCore.QRect(100, 200, 200, 30))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit = QtWidgets.QLineEdit(Initialization)
        self.lineEdit.setGeometry(QtCore.QRect(70, 112, 101, 24))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Initialization)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 112, 101, 24))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(Initialization)
        self.label.setGeometry(QtCore.QRect(20, 110, 61, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Initialization)
        self.label_2.setGeometry(QtCore.QRect(180, 110, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Initialization)
        self.label_3.setGeometry(QtCore.QRect(330, 110, 36, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Initialization)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 231, 41))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Initialization)
        self.buttonBox.accepted.connect(Initialization.accept)
        self.buttonBox.rejected.connect(Initialization.reject)
        QtCore.QMetaObject.connectSlotsByName(Initialization)

    def retranslateUi(self, Initialization):
        _translate = QtCore.QCoreApplication.translate
        Initialization.setWindowTitle(_translate("Initialization", "编辑"))
        self.label.setText(_translate("Initialization", "Qubit:"))
        self.label_2.setText(_translate("Initialization", "|0>+"))
        self.label_3.setText(_translate("Initialization", "|1>"))
        self.label_4.setText(_translate("Initialization", "设置初始值："))
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Ok).setText('确认')
        self.buttonBox.button(QtWidgets.QDialogButtonBox.Cancel).setText('取消')
