# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Qchoice.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Qchoice(object):
    def setupUi(self, Qchoice):
        Qchoice.setObjectName("Qchoice")
        Qchoice.resize(400, 250)
        Qchoice.setMinimumSize(QtCore.QSize(400, 250))
        Qchoice.setMaximumSize(QtCore.QSize(400, 250))
        self.label = QtWidgets.QLabel(Qchoice)
        self.label.setGeometry(QtCore.QRect(140, 30, 101, 61))
        self.label.setObjectName("label")
        self.cancelbutton = QtWidgets.QPushButton(Qchoice)
        self.cancelbutton.setGeometry(QtCore.QRect(140, 190, 93, 28))
        self.cancelbutton.setObjectName("cancelbutton")
        self.widget = QtWidgets.QWidget(Qchoice)
        self.widget.setGeometry(QtCore.QRect(150, 80, 71, 101))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton = QtWidgets.QPushButton(self.widget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QPushButton(self.widget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2)

        self.retranslateUi(Qchoice)
        self.cancelbutton.clicked.connect(Qchoice.reject)
        QtCore.QMetaObject.connectSlotsByName(Qchoice)

    def retranslateUi(self, Qchoice):
        _translate = QtCore.QCoreApplication.translate
        Qchoice.setWindowTitle(_translate("Qchoice", "Dialog"))
        self.label.setText(_translate("Qchoice", "请选择qubit："))
        self.radioButton.setText(_translate("Qchoice", "Q1"))
        self.radioButton_2.setText(_translate("Qchoice", "Q2"))
        self.cancelbutton.setText(_translate("Qchoice", "取消"))
